global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "self-monitoring"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "metric-generator"
    static_configs:
      - targets: ["metric_generator:8000"]

rule_files:
  - "/etc/prometheus/rules/*.yml"
