global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "self-monitoring"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "virtual-store"
    static_configs:
      - targets: ["virtual-store:5000"]

rule_files:
  - "/etc/prometheus/rules/*.yml"
